feat: join growing community section
deltahacks/landing-11 pull request #17
Opened 2024-09-25 16:17 UTC by owengretzinger

### TL;DR

Created the join a growing community section, but there are still some more changes needed in future PRs. Closes https://github.com/deltahacks/landing-11/issues/6.

### What changed?

- Created a new `JoinGrowingCommunity.tsx` component with the content for the section
- Created a `Header.tsx` component
- Added the section to `index.tsx`

### To Do

- Implement mobile design
- Import proper fonts
- Add tree graphics

### Other Notes

- I made changes to `index.tsx` so that the purple background is a lower z-index. This way, we can easily add `-z-10` to graphics and they will automatically show up in front of the purple background, but stay behind any other elements such as text.

### Screenshots

![image](https://github.com/user-attachments/assets/d41b4973-c7bc-40ac-a60e-b97460b6cbb2)

### How to test?

- Pull the code for this PR and make sure everything looks right.

2024-09-25 17:03 UTC, owengretzinger commented
@Shivermist assets for yellow and red dinos are good but the blue dino and the trails I got from Figma are pretty low res. Do you have higher quality ones you could send?

2024-09-26 02:21 UTC, demanr commented
When I look at this on my monitor, the yellow dinos "trail" doesnt extend to the edge of the screen on the right 
![image](https://github.com/user-attachments/assets/688caa01-e7fd-4321-a51e-5351a37b5660)

2024-09-26 13:41 UTC, owengretzinger commented
> When I look at this on my monitor, the yellow dinos "trail" doesnt extend to the edge of the screen on the right 

What should we do about this? @Shivermist are you able to extend the trail? Or should I just stretch it out more on wide screens?

2024-09-28 18:42 UTC, Krish120003 commented
Waiting for #2 before reviewing this

2024-09-28 18:59 UTC, Shivermist commented
> @Shivermist assets for yellow and red dinos are good but the blue dino and the trails I got from Figma are pretty low res. Do you have higher quality ones you could send?

Hi 

> @Shivermist assets for yellow and red dinos are good but the blue dino and the trails I got from Figma are pretty low res. Do you have higher quality ones you could send?

Hi Owen! I've uploaded high quality versions of the assets on the google drive under "Design --> Website assets" and the trails are under it's own folder there. Also the trials are supposed to svgs unless there's some kind of visual artifacts that makes it look weird. Do let me know if that's the case. Thanks!

2024-09-28 19:03 UTC, Shivermist commented
> > When I look at this on my monitor, the yellow dinos "trail" doesnt extend to the edge of the screen on the right
> 
> What should we do about this? @Shivermist are you able to extend the trail? Or should I just stretch it out more on wide screens?

I've also extended the trails considerably on the Figma (assets also available on the drive). If it's still not long enough, feel free to stretch it out to fit on the screen.

2024-10-01 17:08 UTC, owengretzinger commented
Thanks @Shivermist! I updated this PR to use assets from the drive.

@kabirsg I also fixed that issue with the trail showing up over the tree.

2024-10-03 04:27 UTC, kabirsg commented
> Thanks @Shivermist! I updated this PR to use assets from the drive.
> 
> @kabirsg I also fixed that issue with the trail showing up over the tree.

It looks great now thanks Owen!

2024-10-04 19:57 UTC, Krish120003 commented on src/components/Header.tsx
If you've created  a component for this, could you apply using this to the rest of the header/titles as well please

2024-10-04 19:59 UTC, Krish120003 requested changes
@owengretzinger Please install and setup the appropriate font for this section, otherwise this looks great!

https://fontsource.org/fonts/gochi-hand

2024-10-04 22:07 UTC, owengretzinger commented
Updated other headers and added the font (see updated screenshots)

2024-10-06 03:34 UTC, Krish120003 requested changes

2024-10-06 03:34 UTC, Krish120003 commented on package.json
> +    "local": "link:next/font/local",
Remove this dep

2024-10-06 03:34 UTC, Krish120003 commented on src/pages/index.tsx
> +const gochi = localFont({
https://fontsource.org/fonts/gochi-hand/install Switch to this method of installation to be consistent with how other fonts are intalled

2024-10-06 03:34 UTC, Krish120003 commented on src/components/Header.tsx
> +      {title}
Instead of taking title as a prop, why not pass in children as is? That way any word specific styling can be still applied without much changes

2024-10-07 00:42 UTC, owengretzinger commented
fixed @Krish120003

2024-10-07 12:56 UTC, Krish120003 requested changes
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/f6ed28d5-3c4d-451e-b09f-1353ffe0f674">

There's this awkward break in colors on mobile (and on some desktop sizes as well). Could you adjust the background to be a gradient so this doesn't happen?

2024-10-07 14:08 UTC, owengretzinger commented
@Krish120003 I changed the background color to make it match more. However, there's still a little line, which I think is because of a shadow baked into a hero section svg.

The Figma design also has a subtle gradient throughout the whole page. But I think that these things are outside the scope of this PR. Let me know what you think.

![image](https://github.com/user-attachments/assets/190fde56-3bb1-4957-9729-ee4b78863932)

2024-10-07 22:14 UTC, Krish120003 approved these changes

2024-10-07 22:14 UTC, merged