feat: add newsletter
deltahacks/landing-11 pull request #19
Opened 2024-10-02 00:16 UTC by arian81

2024-10-04 19:49 UTC, Krish120003 requested changes

2024-10-04 19:49 UTC, Krish120003 commented on src/components/Newsletter.tsx
> +        <svg
The SVG should be imported or using Next/Image like the other sections

2024-10-04 19:49 UTC, Krish120003 commented on src/components/Newsletter.tsx
> +                <svg
Same with this SVG, please import or using Next/Image like the other sections

2024-10-04 19:49 UTC, Krish120003 commented on src/sections/Footer.tsx
> +        {/* <div className="z-[-1000] mt-32">
Why is it commented out?

2024-10-04 19:49 UTC, Krish120003 commented on src/sections/Footer.tsx
> +      {/* <div className="z-10 col-start-1 row-start-1">
Unnecessary comment

2024-10-04 19:49 UTC, Krish120003 commented on src/sections/Footer.tsx
> +import Newsletter from "~/components/Newsletter";
Newsletter signup should be a section, not a component

2024-10-08 03:53 UTC, Krish120003 requested changes, later dismissed

2024-10-08 03:53 UTC, Krish120003 commented on src/sections/Footer.tsx
> +        <div className="relative mx-auto mt-10 max-w-2xl">
The newsletter signup should be it's own section, not in the footer 😅

2024-10-08 04:09 UTC, Krish120003 commented
@arian81 There's a major discrepancy between sizes of this form on the Figma vs the actual site. Please confirm with @Shivermist how big the form should be and either update the site or have the design files updated.

2024-10-08 04:11 UTC, Krish120003 commented
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/035fab96-f547-4d73-a912-fc644ebd6b7e">
There's also a weird breakpoint where the rounding is removed completely, but the page isnt small enough for the form dialog to be seamlessly flush with the edges of the page. Could you update the styling to handle this?

2024-10-13 00:43 UTC, arian81 commented
> <img alt="image" width="1470" src="https://private-user-images.githubusercontent.com/52761222/374403614-035fab96-f547-4d73-a912-fc644ebd6b7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3Nzk3MzksIm5iZiI6MTcyODc3OTQzOSwicGF0aCI6Ii81Mjc2MTIyMi8zNzQ0MDM2MTQtMDM1ZmFiOTYtZjU0Ny00ZDczLWE5MTItZmM2NDRlYmQ2YjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAwMzAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMzk0OGU2NzI0YmYwYmRkNDZkOTM0NmZmOTE3NDM3ODIxYmZkYzY5NDY3MDk5Njk4MDA4ZDgwZGFjY2FjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a4jFiyOBqgiJUnUolhXC-HpqNNnUlfRTgTa6S3B94Oc"> There's also a weird breakpoint where the rounding is removed completely, but the page isnt small enough for the form dialog to be seamlessly flush with the edges of the page. Could you update the styling to handle this?

not sure what to do about this because it's not caught by the tailwind breakpoints. it doesn't happen in any of the device sizes that I've checked so I think it should be good as is ?

2024-10-18 14:06 UTC, kabirsg approved these changes
LGTM

2024-10-19 05:09 UTC, merged